version: '3'
services:
  java:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /home/papercut/Documentos/projects/kotlin/delorean-bookstore:/home/project_repo/
    network_mode: host
    stdin_open: true
    tty: true
